language: node_js
dist: trusty
node_js:
  - "node"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a1a629c5886b84b29d1e
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always


services:
  - mysql

before_install:
  # Create databases.
  - mysql -u root -e 'CREATE DATABASE codgic;'
  - mysql -u root -e 'CREATE DATABASE codgic_test;'

  # Create user 'codgic'.
  - mysql -u root -e  "CREATE USER 'codgic'@'localhost' IDENTIFIED BY 'YOURPASSWORD';"

  # Grant privileges on user 'codgic'.
  - mysql -u root -e "GRANT ALL ON *.* TO 'codgic'@'localhost';"

before_script:
  # Install dependencies.
  - yarn install

script:
  # Generate config.yml.
  - gulp renameConfig

  # Compile project.
  - yarn run build

  # Run tests.
  - yarn run test
