# Codgic-api Configuration
# Version 0.0.0 - Unreleased!

# OJ
oj:
  name: Codgic
  language: en
  timezone: Asia/Shanghai
  policy:
    access_need_login: false
    signup_need_confirmation: false
    signup_need_verify_email: false
  default:
    page:
      contest: 50
      problem: 50
      user: 20
    contest:
      duration: 7200
    problem:
      memory_limit: 256
      time_limit: 1000
    
# API
api:
  port: 8080
  jwt:
    secret: FuckZh@ngKeW@terQueen
    expire_time: 3600h

# Database
database:
  host: localhost
  port: 3306
  database: codgic
  username: codgic
  password: YOURPASSWORD
  type: mysql
  log:
    queries: true
    failed_query_error: true
