# Codgic-api Configuration
# Version 0.0.0 - Unreleased!

# OJ Settings
OJ:
  NAME: Codgic
  LANGUAGE: en
  TIMEZONE: Asia/Shanghai

# API Settings
API:
  PORT: 8080

# Database
DATABASE:
  HOST: localhost
  PORT: 3306
  NAME: codgic
  USERNAME: codgic
  PASSWORD: YOURPASSWORD
  TYPE: mysql
