# Codgic-api Configuration
# Version 0.0.0 - Unreleased!

# OJ
oj:
  name: Codgic
  language: en
  timezone: Asia/Shanghai
  page:
    contest: 50
    problem: 50
    
# API
api:
  port: 8080

# Database
database:
  host: localhost
  port: 3306
  database: codgic
  username: codgic
  password: YOURPASSWORD
  type: mysql
